#!/usr/bin/env python3
"""Generate Android's language content from the existing Swift modules.

Only declarative string content is translated; Kotlin owns the runtime policy and models.
Modules are discovered from `LanguageRegistry.all` in `apps/ios/Core/Languages/LanguageModule.swift`,
so adding a Swift module and registering it is enough to export it. Run --check in CI to
detect drift between platforms.
"""
import argparse
import json
import pathlib
import re

KOTLIN_DEST = 'apps/android/app/src/main/java/chat/mural/core/Languages.kt'
# Fields whose value is a nested structure (array/dict), extracted separately from the
# simple quoted-string fields.
STRUCTURED_FIELDS = ('teachingFocus', 'themeOverrides')


def quoted(text):
    return json.dumps(text, ensure_ascii=False).replace('$', r'\$')


def swift_strings(text):
    return [json.loads('"' + value + '"') for value in re.findall(r'"((?:[^"\\]|\\.)*)"', text)]


def theme(text):
    vals = swift_strings(text)
    color = int(re.search(r',\s*(\d+)\s*\)$', text).group(1))
    if len(vals) != 6:
        raise SystemExit(f'Unexpected ConversationTheme arguments {vals}; expected six strings and a color index.')
    return 'ConversationTheme(' + ', '.join(map(quoted, vals)) + ', ' + str(color) + ')'


def struct_fields(language_module_swift_text):
    """Stored properties of the `LanguageModule` struct, in declaration order."""
    return re.findall(r'\bpublic let (\w+):', language_module_swift_text)


def language_files(core):
    """`apps/ios/Core/Languages/*.swift` files, ordered as declared in `LanguageRegistry.all`."""
    text = (core / 'Languages/LanguageModule.swift').read_text(encoding='utf-8')
    match = re.search(r'public static let all:\s*\[LanguageModule\]\s*=\s*\[([^\]]*)\]', text)
    if not match:
        raise SystemExit('LanguageRegistry.all not found in apps/ios/Core/Languages/LanguageModule.swift.')
    names = re.findall(r'\.(\w+)', match.group(1))
    return [core / 'Languages' / f'{name[0].upper()}{name[1:]}.swift' for name in names]


def call_arguments(module_swift_text):
    """Argument labels used in a module file's `LanguageModule(...)` initializer call.

    Matches a label at the start of a line, or after a comma on the same line, so that
    quoted `themeOverrides` dictionary keys (which start their own line but are not
    followed by a same-line label) are never mistaken for an argument.
    """
    return set(re.findall(r'(?:^|,)[ \t]*(\w+):[ \t]', module_swift_text, re.MULTILINE))


def meaning_languages(text):
    """Kotlin lines for `MeaningLanguages`, read from the Swift enum so both clients offer the same list."""
    block = re.search(r'enum MeaningLanguages\s*\{(.*?)\n\}', text, re.S)
    if not block:
        raise SystemExit('MeaningLanguages not found in Core/Languages/LanguageModule.swift.')
    names = re.search(r'static let all\s*=\s*\[(.*?)\]', block.group(1), re.S)
    greetings = re.search(r'func greeting\(in language: String\)[^\[]*\[(.*?)\]\[language\]\s*\?\?\s*("(?:[^"\\]|\\.)*")', block.group(1), re.S)
    if not names or not greetings:
        raise SystemExit('MeaningLanguages.all or greeting(in:) has an unexpected shape in Core/Languages/LanguageModule.swift.')
    pairs = re.findall(r'("(?:[^"\\]|\\.)*")\s*:\s*("(?:[^"\\]|\\.)*")', greetings.group(1))
    if not pairs:
        raise SystemExit('MeaningLanguages greetings not found in Core/Languages/LanguageModule.swift.')
    return ['    val all = listOf(' + ', '.join(map(quoted, swift_strings(names.group(1)))) + ')',
            '    fun greeting(language: String) = mapOf(' + ', '.join(f'{quoted(json.loads(k))} to {quoted(json.loads(v))}' for k, v in pairs)
            + f')[language] ?: {quoted(json.loads(greetings.group(2)))}']


def generate(core):
    """Render `Languages.kt` from the Swift language content under `core`."""
    registry_text = (core / 'Languages/LanguageModule.swift').read_text(encoding='utf-8')
    known_fields = struct_fields(registry_text)
    default_match = re.search(r'static let defaultID\s*=\s*"([^"]+)"', registry_text)
    if not default_match:
        raise SystemExit('LanguageRegistry.defaultID not found in Core/Languages/LanguageModule.swift.')
    default_id = default_match.group(1)
    simple_fields = [f for f in known_fields if f not in STRUCTURED_FIELDS]

    shared = (core / 'Themes.swift').read_text(encoding='utf-8')
    shared_themes = [theme(line.strip().removesuffix(',')[len('.init(') - 1:])
                      for line in shared.splitlines() if line.strip().startswith('.init(')]
    lines = ['// Generated by scripts/export_android_content.py; edit the Swift language content.',
             'package chat.mural.core', '',
             'data class ConversationTheme(val id: String, val title: String, val subtitle: String, val symbol: String, val category: String, val situation: String, val colorIndex: Int)',
             'object Themes { val shared = listOf(', ',\n'.join('    ' + x for x in shared_themes), ') }', '',
             '''data class LanguageModule(
    val id: String, val name: String, val nativeName: String, val variety: String, val locale: String,
    val greeting: String, val greetingWord: String, val speechGuidance: String, val writingGuidance: String,
    val lemmaGuidance: String, val teachingFocus: List<String>, val topicPlaceholder: String,
    val lookupUnavailableReply: String, val themeOverrides: Map<String, ConversationTheme> = emptyMap()
) {
    val themes get() = Themes.shared.map { themeOverrides[it.id] ?: it }
    val defaultTitle get() = "A little $name"
    val talkTitle get() = "A little everyday $name"
    val settingsTitle get() = "$name · $variety"
}''', '', 'object LanguageRegistry {', f'    const val defaultID = {quoted(default_id)}']
    module_names = []
    for path in language_files(core):
        text = path.read_text(encoding='utf-8')
        unknown = call_arguments(text) - set(known_fields)
        if unknown:
            raise SystemExit(
                f"Unknown LanguageModule field(s) {', '.join(sorted(unknown))} in {path}. "
                f"Declare them in apps/ios/Core/Languages/LanguageModule.swift and add support in {KOTLIN_DEST}.")
        module_name = path.stem.lower()
        module_names.append(module_name)
        args = []
        for key in simple_fields:
            match = re.search(r'\b' + key + r':\s*("(?:[^"\\]|\\.)*")', text)
            if not match:
                raise SystemExit(f'LanguageModule field {key} not found in {path}. Add it or update {KOTLIN_DEST}.')
            args.append(f'        {key} = {quoted(json.loads(match.group(1)))}')
        focus_match = re.search(r'teachingFocus:\s*\[(.*?)\]', text, re.S)
        focuses = swift_strings(focus_match.group(1)) if focus_match else []
        if len(focuses) != 6:
            raise SystemExit(f'{path} must define exactly six teachingFocus stages.')
        args.append('        teachingFocus = listOf(' + ', '.join(map(quoted, focuses)) + ')')
        overrides = []
        for line in text.splitlines():
            m = re.match(r'\s*"([^"]+)":\s*\.init(.*)', line)
            if m:
                overrides.append(quoted(m.group(1)) + ' to ' + theme(m.group(2).removesuffix(',')))
        args.append('        themeOverrides = mapOf(' + ',\n            '.join(overrides) + ')')
        lines += [f'    private val {module_name} = LanguageModule(', ',\n'.join(args), '    )']
    lines += [f'    val all = listOf({", ".join(module_names)})',
              '    fun get(id: String) = all.firstOrNull { it.id == id }', '}', '',
              'object MeaningLanguages {']
    lines += meaning_languages(registry_text)
    lines += ['}', '']
    return '\n'.join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--root', type=pathlib.Path, default=pathlib.Path(__file__).resolve().parents[1])
    args = parser.parse_args(argv)
    dest = args.root / KOTLIN_DEST
    result = generate(args.root / 'apps/ios/Core')
    if args.check:
        if not dest.exists() or dest.read_text(encoding='utf-8') != result:
            raise SystemExit('Android language content differs. Run python3 scripts/export_android_content.py')
    else:
        dest.write_text(result, encoding='utf-8')


if __name__ == '__main__':
    main()
